"""Capability catalog exposed to the planner."""
from __future__ import annotations
from .models import PlanningCapability, StepCapability


def default_capabilities() -> tuple[PlanningCapability, ...]:
    return (
        PlanningCapability("open_calculator", StepCapability.TOOL, "Open Windows Calculator."),
        PlanningCapability("create_folder", StepCapability.TOOL, "Create a folder at a user-specified path.", {"path": "string"}, True),
        PlanningCapability("system.open_app", StepCapability.TOOL, "Open a Windows application by name or executable path.", {"app": "string"}),
        PlanningCapability("system.open_path", StepCapability.TOOL, "Open a local file or folder with its default application.", {"path": "string"}),
        PlanningCapability("system.list_processes", StepCapability.TOOL, "List running Windows process names."),
        PlanningCapability("files.exists", StepCapability.TOOL, "Check whether a file or folder exists.", {"path": "string"}),
        PlanningCapability("files.list_directory", StepCapability.TOOL, "List items inside a directory.", {"path": "string", "limit": "optional integer"}),
        PlanningCapability("files.search", StepCapability.TOOL, "Search recursively for files and folders by name.", {"root": "string", "query": "string", "limit": "optional integer"}),
        PlanningCapability("files.read_text", StepCapability.TOOL, "Read a local text file.", {"path": "string", "max_chars": "optional integer"}),
        PlanningCapability("files.write_text", StepCapability.TOOL, "Create or overwrite a local text file.", {"path": "string", "text": "string"}, True),
        PlanningCapability("files.copy", StepCapability.TOOL, "Copy a local file or directory.", {"source": "string", "destination": "string"}, True),
        PlanningCapability("files.move", StepCapability.TOOL, "Move or rename a local file or directory.", {"source": "string", "destination": "string"}, True),
        PlanningCapability("browser.start", StepCapability.BROWSER, "Start the managed Playwright browser."),
        PlanningCapability("browser.new_tab", StepCapability.BROWSER, "Open a new tab in the managed browser.", {"url": "optional string"}),
        PlanningCapability("browser.goto", StepCapability.BROWSER, "Navigate the managed browser to a URL.", {"url": "string"}),
        PlanningCapability("browser.read_page", StepCapability.BROWSER, "Read the current page title, URL, and visible text."),
        PlanningCapability("browser.click", StepCapability.BROWSER, "Click a page element semantically by role, label, text, placeholder, test id, or CSS selector.", {"kind": "string", "value": "string", "name": "optional string"}),
        PlanningCapability("browser.fill", StepCapability.BROWSER, "Fill a page input semantically.", {"kind": "string", "value": "string", "text": "string"}),
        PlanningCapability("browser.press", StepCapability.BROWSER, "Press a key in the browser.", {"key": "string"}),
        PlanningCapability("browser.scroll", StepCapability.BROWSER, "Scroll the current webpage.", {"delta_y": "integer"}),
        PlanningCapability("browser.download", StepCapability.BROWSER, "Trigger and save a browser download.", {"target": "object"}, True),
        PlanningCapability("youtube.play_latest_upload", StepCapability.BROWSER, "Open the newest standard video upload from a YouTube channel using its handle or name.", {"channel": "string"}),
        PlanningCapability("youtube.play_oldest_upload", StepCapability.TOOL, "Resolve a channel and play its oldest normal upload in the Windows default browser.", {"channel": "string"}),
        PlanningCapability("youtube.play_most_popular", StepCapability.TOOL, "Resolve a channel, verify view counts, and play its most-viewed normal upload.", {"channel": "string"}),
        PlanningCapability("youtube.play_live", StepCapability.TOOL, "Resolve a channel and play its current verified live stream only.", {"channel": "string"}),
        PlanningCapability("youtube.play_matching_video", StepCapability.TOOL, "Find and play a vaguely remembered YouTube video from a natural-language description.", {"description": "string", "search_query": "optional string", "channel": "optional string"}),
        PlanningCapability("messaging.resolve_contact", StepCapability.TOOL, "Resolve a contact in a visible logged-in messaging client.", {"service":"string","recipient":"string"}),
        PlanningCapability("messaging.open_chat", StepCapability.TOOL, "Open a recipient chat in a visible messaging client.", {"service":"string","recipient":"string"}),
        PlanningCapability("messaging.read_recent", StepCapability.TOOL, "Read recent visibly available messages from a requested chat.", {"service":"string","recipient":"string","count":"optional integer"}),
        PlanningCapability("messaging.send", StepCapability.TOOL, "Send a prepared message only after explicit final confirmation.", {"service":"string","recipient":"string","message":"string"}),
        PlanningCapability("youtube.search", StepCapability.TOOL, "Search YouTube in the background and return structured video results.", {"query": "string", "limit": "optional integer"}),
        PlanningCapability("youtube.play", StepCapability.TOOL, "Find and visibly play a YouTube video in the Windows default browser.", {"video": "string"}),
        PlanningCapability("youtube.get_info", StepCapability.TOOL, "Retrieve structured YouTube video metadata in the background.", {"video": "string"}),
        PlanningCapability("youtube.get_transcript", StepCapability.TOOL, "Retrieve a YouTube video transcript in the background.", {"video": "string", "languages": "optional array"}),
        PlanningCapability("youtube.summarize", StepCapability.TOOL, "Retrieve transcript evidence so the AI can summarize a YouTube video.", {"video": "string", "languages": "optional array"}),
        PlanningCapability("youtube.trending", StepCapability.TOOL, "Retrieve trending YouTube videos in the background.", {"region": "optional string", "limit": "optional integer"}),
        PlanningCapability("youtube.pause", StepCapability.TOOL, "Pause Conduit's current YouTube playback."),
        PlanningCapability("youtube.resume", StepCapability.TOOL, "Resume Conduit's current YouTube playback."),
        PlanningCapability("vision.observe", StepCapability.VISION, "Capture and structurally analyze the visible desktop."),
        PlanningCapability("vision.find", StepCapability.VISION, "Locate a visible desktop element by a natural-language target.", {"target": "string"}),
        PlanningCapability("desktop.click", StepCapability.DESKTOP, "Click a previously located desktop element.", {"target": "string"}, True),
        PlanningCapability("desktop.type", StepCapability.DESKTOP, "Type text into the focused desktop application.", {"text": "string"}, True),
        PlanningCapability("desktop.press", StepCapability.DESKTOP, "Press a keyboard key in the focused application.", {"key": "string"}, True),
        PlanningCapability("desktop.hotkey", StepCapability.DESKTOP, "Press a keyboard shortcut.", {"keys": "array of strings"}, True),
        PlanningCapability("desktop.scroll", StepCapability.DESKTOP, "Scroll the focused desktop application.", {"clicks": "integer"}, True),
        PlanningCapability("ask_user", StepCapability.USER, "Ask the user for missing information or a decision.", {"question": "string"}),
    )
